version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    secrets:
      - www_learnaword_net.key
      - www_learnaword_net.pem
    volumes:
      - /mnt/volume_ams3_01/nginx.conf:/etc/nginx/nginx.conf
  web:
    secrets:
      - password
      - session_secret
      - auth0_client_secret
      - appsignal_push_api_key
    environment:
      PASSWORD_PATH: /run/secrets/password
      SESSION_SECRET_PATH: /run/secrets/session_secret
      AUTH0_CLIENT_SECRET_PATH: /run/secrets/auth0_client_secret
      APPSIGNAL_PUSH_API_KEY: /run/secrets/appsignal_push_api_key
      APPSIGNAL_APP_NAME: Cards
      RACK_ENV: none
      APP_ENV: production
      REDIS_HOST: redis
    image: kostyadubinin/cards
    ports:
      - "9292:9292"
    networks:
      - webnet
  redis:
    image: redis
    volumes:
        - /mnt/volume_ams3_01:/data
    networks:
      - webnet
networks:
  webnet:
secrets:
   password:
     external: true
   session_secret:
     external: true
   auth0_client_secret:
     external: true
   www_learnaword_net.key:
     external: true
   www_learnaword_net.pem:
     external: true
   appsignal_push_api_key:
     external: true
